export const MOVIE_TYPES = {
    FETCH_MOVIES: 'FETCH_MOVIES',
    SEARCH_MOVIES: 'SEARCH_MOVIES',
    SET_MOVIES: 'SET_MOVIES',
    LOADING_MOVIES: 'LOADING_MOVIES',
    FEATURED_MOVIES: 'FEATURED_MOVIES'
}